import flet as ft
from localisations import *
from components import mystack


def home(adaptive: bool, page: ft.Control):
    return ft.View(
        route="/",
        adaptive=adaptive,
        appbar=ft.AppBar(title=ft.Text("Chaos+"), center_title=True),
        auto_scroll=True,
        controls=[
            ft.SafeArea(
                ft.Column(
                    controls=[
                        ft.Text("Hello", size=40),
                        ft.Row(
                            controls=[
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                            ],
                            expand=True,
                            scroll=ft.ScrollMode.AUTO,
                        ),
                        ft.Text("Hello", size=40),
                        ft.Row(
                            controls=[
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                            ],
                            expand=True,
                            scroll=ft.ScrollMode.AUTO,
                        ),
                        ft.Text("Hello", size=40),
                        ft.Row(
                            controls=[
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                                mystack(
                                    img_src="https://picsum.photos/300/300",
                                    text=HELLOMSG(page),
                                ),
                            ],
                            expand=True,
                            scroll=ft.ScrollMode.AUTO,
                        ),
                    ],
                )
            )
        ],
        scroll=ft.ScrollMode.AUTO,
    )
